export const facilities = [
  {
    id: 1,
    title: "Primary Classroom",
    category: "classrooms",
    img: "/images/gallery/classroom1.jpg",
    description: "Bright and spacious classrooms designed for active learning and focus.",
  },
  {
    id: 2,
    title: "Junior High Classroom",
    category: "classrooms",
    img: "/images/gallery/classroom2.jpg",
    description: "Modern JHS classrooms with interactive boards and comfortable seating.",
  },
  {
    id: 3,
    title: "Playground Fun",
    category: "playground",
    img: "/images/gallery/playground1.jpg",
    description: "Safe and fun playground where students enjoy games and physical activity.",
  },
  {
    id: 4,
    title: "Science Fair Event",
    category: "events",
    img: "/images/gallery/event1.jpg",
    description: "Annual science fair showcasing students’ creativity and innovation.",
  },
  {
    id: 5,
    title: "Football Practice",
    category: "sports",
    img: "/images/gallery/sports1.jpg",
    description: "Training and sports events to promote teamwork and fitness.",
  },
  {
    id: 6,
    title: "Art Class",
    category: "arts",
    img: "/images/gallery/arts1.jpg",
    description: "Creative art sessions that encourage imagination and expression.",
  },
  {
    id: 7,
    title: "Teachers",
    category: "teachers",
    img: "/images/gallery/teachers1.jpg",
    description: "Dedicated teaching staff guiding students academically and morally.",
  },
  {
    id: 8,
    title: "Boarding House",
    category: "boarding",
    img: "/images/gallery/boarding1.jpg",
    description: "Comfortable boarding accommodations fostering a safe, nurturing environment.",
  },
  {
    id: 9,
    title: "I.C.T. Lab",
    category: "classrooms",
    img: "/images/gallery/ictlab1.jpg",
    description: "Modern ICT lab equipped with the latest technology for digital learning.",
  },
];
